substitutions:
  name: heatpump-s3-zero
  friendly_name: My Heatpump S3 Zero
  remote_temp_sensor: sensor.my_room_temperature # Homeassistant sensor providing remote temperature

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  on_boot:
    priority: 600 # High priority runs early in the boot process
    then:
      - lambda: |- #this lambda is used to connect the remote uart to RE_UART.  This is necessary unless Climate.py is changed
          extern esphome::uart::IDFUARTComponent* g_re_uart;
          g_re_uart = id(RE_UART);
      - light.turn_on:
          id: statusledlight
          red: 100%
          green: 0%
          blue: 0%
          brightness: 40%
  platformio_options:
    build_flags:
      -DBOARD_HAS_PSRAM
      -DWEBPORT=8080 #optional, starts a debug web interface on port 8080
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: qio
    board_build.psram_type: qio
    board_upload.maximum_size: 4194304
  
esp32:
#  board: esp32doit-devkit-v1
#  framework:
#    type: esp-idf
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 4MB
  framework:
    type: esp-idf

uart:
  - id: HP_UART
    baud_rate: 2400
    parity: even
    tx_pin: GPIO13
    rx_pin: GPIO12
  - id: RE_UART
    baud_rate: 2400
    parity: even
    tx_pin: GPIO11
    rx_pin: GPIO10

external_components:
  - source: github://Kirbyrc/MitsubishiCN105ESPHome-Remote
    refresh: 0s

#status LED
light:
  - platform: esp32_rmt_led_strip
    rgb_order: RGB
    pin: GPIO21
    num_leds: 1
    chipset: ws2812
    name: Status LED Light
    id: statusledlight
    restore_mode: ALWAYS_ON
          

# Enable WiFi connection
wifi:
  output_power: 8.5
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
    then:
      - light.turn_on:
          id: statusledlight
          red: 50%
          green: 50%
          blue: 0%
          brightness: 40%


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} ESP"
    password: !secret recovery_password

captive_portal:

# Enable logging
logger:
#   hardware_uart: UART1
#   level: INFO
  logs:
    EVT_SETS : INFO
    WIFI : INFO
    MQTT : INFO
    WRITE_SETTINGS : INFO
    SETTINGS : INFO
    STATUS : INFO
    CN105Climate: WARN
    CN105: INFO
    climate: WARN
    sensor: WARN
    chkSum : INFO
    WRITE : WARN
    READ : WARN
    Header: INFO
    Decoder : INFO
    CONTROL_WANTED_SETTINGS: INFO
    HPE_Core : WARN  # new logging for the Heatpump Emulator messages
#  level: DEBUG
#  logs:
#    EVT_SETS : DEBUG
#    WIFI : INFO
#    MQTT : INFO
#    WRITE_SETTINGS : INFO
#    SETTINGS : DEBUG
#    STATUS : INFO
#    CN105Climate: WARN
#    CN105: DEBUG
#    climate: WARN
#    sensor: WARN
#    chkSum : INFO
#    WRITE : INFO
#    READ : WARN
#    Header: INFO
#    Decoder : DEBUG
#    CONTROL_WANTED_SETTINGS: DEBUG
#    HPE_Core : DEBUG # new logging for the Heatpump Emulator messages

# Enable Home Assistant API
api:
  encryption:
    key: !secret ha_encryption_key
  on_client_connected:
    then:
      - light.turn_on:
          id: statusledlight
          red: 0%
          green: 100%
          blue: 0%
          brightness: 40%
  
  on_client_disconnected:
    then:
      - light.turn_on:
          id: statusledlight
          red: 100%
          green: 0%
          blue: 0%
          brightness: 40%

ota:
  password: !secret ota_password
  platform: esphome


sensor:
  # Sensors with general information.

  # Uptime sensor.
  - platform: uptime
    name: Uptime
  # WiFi Signal sensor.
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 120s
  - platform: homeassistant
    name: "Remote Temperature Sensor"
    entity_id: ${remote_temp_sensor} # Replace with your HomeAssistant remote sensor entity id, or include in substitutions
    internal: false
    disabled_by_default: true
    device_class: temperature
    state_class: measurement
    unit_of_measurement: "°C"
    filters:
    # Uncomment the lambda line to convert F to C on incoming temperature
    #  - lambda: return (x - 32) * (5.0/9.0);
      - clamp: # Limits values to range accepted by Mitsubishi units
          min_value: 1
          max_value: 40
          ignore_out_of_range: true
      - throttle: 30s
    on_value:
      then:
        - logger.log:
            level: INFO
            format: "Remote temperature received from HA: %.1f C"
            args: [ 'x' ]
        - lambda: 'id(hp).set_remote_temperature(x);'

# Enable Web server.
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: IP
    ssid:
      name: SSID
    bssid:
      name: BSSID


# Create a button to restart the unit from HomeAssistant. Rarely needed, but can be handy.
button:
  - platform: restart
    name: "Restart ${friendly_name}"

# Creates the sensor used to receive the remote temperature from Home Assistant
# Uses sensor selected in substitutions area at top of config
# Customize the filters to your application:
#   Uncomment the first line to convert F to C when remote temps are sent
#   If you have a fast or noisy sensor, consider some of the other filter
#   options such as throttle_average.
climate:
  - platform: cn105
    id: hp
    uart_id: HP_UART
    name: "${friendly_name}"
    icon: mdi:heat-pump
    visual:
      min_temperature: 15
      max_temperature: 31
      temperature_step:
        target_temperature: 1
        current_temperature: 0.5
    # Timeout and communication settings
    remote_temperature_timeout: 30min
    update_interval: 4s
    debounce_delay : 100ms
    # Various optional sensors, not all sensors are supported by all heatpumps
    compressor_frequency_sensor:
      name: Compressor Frequency
      entity_category: diagnostic
      disabled_by_default: true
    outside_air_temperature_sensor:
      name: Outside Air Temp
      disabled_by_default: true
    vertical_vane_select:
      name: Vertical Vane
      disabled_by_default: false
    horizontal_vane_select:
      name: Horizontal Vane
      disabled_by_default: true
    isee_sensor:
      name: ISEE Sensor
      disabled_by_default: true
    stage_sensor:
      name: Stage
      entity_category: diagnostic
      disabled_by_default: true
    sub_mode_sensor:
      name: Sub Mode
      entity_category: diagnostic
      disabled_by_default: true
    auto_sub_mode_sensor:
      name: Auto Sub Mode
      entity_category: diagnostic
      disabled_by_default: true
    input_power_sensor:
      name: Input Power
      disabled_by_default: true
    kwh_sensor:
      name: Energy Usage
      disabled_by_default: true
    runtime_hours_sensor:
      name: Runtime Hours
      entity_category: diagnostic
      disabled_by_default: true
